version: '1.0'
actions:
  generate_cohort:
    run: cohortextractor:latest generate_cohort --output-dir=/workspace
    outputs:
      highly_sensitive:
        cohort: input.csv

  data_setup:
    run: r:latest analysis/data_setup.R input.csv
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        log: data_setup_log.txt
        data: community_prevalence.rds
      highly_sensitive:
        analysis_data: analysisdata.rds
        input_data: input_clean.rds
        ch_data: ch_linelist.rds
        cg_agg_data: ch_agg_long.rds

  descriptive:
    needs: [data_setup]
    run: r:latest analysis/descriptive.R input_clean.rds ch_linelist.rds ch_agg_long.rds community_prevalence.rds
    outputs:
      moderately_sensitive:
        report: descriptive.pdf
        log: log_descriptive.txt
        data: ch_gp_permsoa.csv


  run_models_0_cutoff:
    needs: [data_setup]
    run: r:latest analysis/run_models.R analysisdata.rds community_prevalence.rds 0
    outputs:
      moderately_sensitive:
        coeffs: coeffs_bestmod_0.csv
        output: output_model_run_0.txt
        log: log_model_run_0.txt
      highly_sensitive:
        fit: fit_opt_0.rds
        
  validate_models_0_cutoff:
    needs: [run_models_0_cutoff]
    run: r:latest analysis/validate_models.R fit_opt_0.rds 0
    outputs:
      moderately_sensitive:
        report: test_pred_figs_0.pdf


  run_models_50_cutoff:
    needs: [data_setup]
    run: r:latest analysis/run_models.R analysisdata.rds community_prevalence.rds 50
    outputs:
      moderately_sensitive:
        coeffs: coeffs_bestmod_50.csv
        output: output_model_run_50.txt
        log: log_model_run_50.txt
      highly_sensitive:
        fit: fit_opt_50.rds
        
  validate_models_50_cutoff:
    needs: [run_models_50_cutoff]
    run: r:latest analysis/validate_models.R fit_opt_50.rds 50
    outputs:
      moderately_sensitive:
        report: test_pred_figs_50.pdf


  run_models_100_cutoff:
    needs: [data_setup]
    run: r:latest analysis/run_models.R analysisdata.rds community_prevalence.rds 100
    outputs:
      moderately_sensitive:
        coeffs: coeffs_bestmod_100.csv
        output: output_model_run_100.txt
        log: log_model_run_100.txt
      highly_sensitive:
        fit: fit_opt_100.rds
        
  validate_models_100_cutoff:
    needs: [run_models_100_cutoff]
    run: r:latest analysis/validate_models.R fit_opt_100.rds 100
    outputs:
      moderately_sensitive:
        report: test_pred_figs_100.pdf
        
  run_models_200_cutoff:
    needs: [data_setup]
    run: r:latest analysis/run_models.R analysisdata.rds community_prevalence.rds 200
    outputs:
      moderately_sensitive:
        coeffs: coeffs_bestmod_200.csv
        output: output_model_run_200.txt
        log: log_model_run_200.txt
      highly_sensitive:
        fit: fit_opt_200.rds
        
  validate_models_200_cutoff:
    needs: [run_models_200_cutoff]
    run: r:latest analysis/validate_models.R fit_opt_200.rds 200
    outputs:
      moderately_sensitive:
        report: test_pred_figs_200.pdf
