version: '3.0'

expectations:
  population_size: 1000000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition 
    outputs:
      highly_sensitive:
        cohort: input.csv

  generate_coverage_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_coverage
    outputs:
      highly_sensitive:
        cohort: input_coverage.csv

  calc_coverage:
    run: r:latest analysis/calculate_tpp_coverage.R input_coverage.csv data/SAPE22DT15_mid_2019_msoa.csv
    needs: [generate_coverage_population]
    outputs:
      moderately_sensitive:
        log: coverage_log.txt
        rds: tpp_msoa_coverage.rds
        csv: tpp_msoa_coverage.csv
        csv2: msoas_in_tpp.csv
        csv3: msoa_gt_100_cov.csv
        figure: total_vs_tpp_pop.png
#        map: map_coverage_msoa.pdf

  data_check:
    run: r:latest analysis/data_check.R input.csv tpp_msoa_coverage.rds data/msoa_shp.rds 80
    needs: [generate_study_population, calc_coverage]
    outputs:
      moderately_sensitive:
        log: data_checks.txt
        figure1: tpp_coverage_msoa.png
        figure2: tpp_coverage_carehomes.png
        figure3: tpp_coverage_map.pdf
        figure4: age_dist.png
        figure5: infection_death_delays.png
        figure6: hh_size_dist.png

  data_setup:
  # last numeric arguments relate to cut off for MSOA and carehome TPP coverage >= X%
    run: r:latest analysis/data_setup.R input.csv tpp_msoa_coverage.rds 80 90
    needs: [generate_study_population, calc_coverage]
    outputs:
      moderately_sensitive:
        log: data_setup_log.txt
        rds: community_prevalence.rds
        csv: community_prevalence.csv
      highly_sensitive:
        analysisdata: analysisdata.rds
        input_clean: input_clean.rds
        ch_linelist: ch_linelist.rds
        ch_agg_long: ch_agg_long.rds

  descriptive:
    needs: [data_setup]
    run: r:latest analysis/descriptive.R input_clean.rds ch_linelist.rds ch_agg_long.rds community_prevalence.rds
    outputs:
      moderately_sensitive:
        report: descriptive.pdf
        log: log_descriptive.txt
        data: ch_gp_permsoa.csv


  run_models_nocutoff:
    needs: [data_setup]
    run: r:latest analysis/run_models.R analysisdata.rds community_prevalence.rds data/msoa_shp.rds 0 0.1
    outputs:
      moderately_sensitive:
       # coeffs: coeffs_bestmod_0.csv
        output: output_model_run_0.txt
        log: log_model_run_0.txt
        figure: model_resids_map_0.pdf
      highly_sensitive:
        fit: fits_0.rds
        data: testdata_0.rds

  validate_models_nocutoff:
    needs: [run_models]
    run: r:latest analysis/validate_models.R fits_0.rds testdata_0.rds 0
    outputs:
      moderately_sensitive:
        output: output_model_val_0.txt
        report: test_pred_figs_0.pdf

  run_models:
    needs: [data_setup]
    run: r:latest analysis/run_models.R analysisdata.rds community_prevalence.rds data/msoa_shp.rds 0.1
    outputs:
      moderately_sensitive:
        output: output_model_run.txt
        log: log_model_run.txt
       # figure: model_resids_map.pdf
      highly_sensitive:
        fit: fits.rds
        data: testdata.rds

  validate_models:
    needs: [run_models]
    run: r:latest analysis/validate_models.R fits.rds testdata.rds
    outputs:
      moderately_sensitive:
        output: output_model_val.txt
        report: test_pred_figs.pdf
        
  run_all:
    needs: [validate_models, descriptive]
    # In order to be valid this action needs to define a run commmand and
    # some output. We don't really care what these are but the below seems to
    # do the trick.
    run: cohortextractor:latest --version
    outputs:
      moderately_sensitive:
        whatever: project.yaml
